### ISSUE TITLE
Trouble getting cadence info

### ISSUE THREAD

**Issue by mikefulb** [snowzach/echbt#3]
I tried the sketch recently and had trouble getting the cadence notifications enabled.  I did see resistance values but the callbacks with data[1] == 0xD1 never gave a different value for cadence even after pedaling awhile.

Do you know that the existing code works with recent Echelon Sport Connect bikes?

Thanks!

**Comment by snowzach** [comment]
I have a sport connect that's less than 6 months old. In order for the bike to send cadence information you have to send an initial value to the bike. It only occasionally sends the cadence update. The only thing I can imagine is that they somehow changed the value you need to send to get it started maybe.

**Comment by mikefulb** [comment]
Thank you for the quick feedback.

I was thinking maybe they had changed the value as well.

However I will say your Android app works great so I was curious if it is using the same mechanism as echbt here does.  If so then that might mean they haven't changed anything and perhaps I have made an error.

**Comment by snowzach** [comment]
Yeah, if the android app is working then it's something in the code there.
They are basically the same.

**Comment by mikefulb** [comment]
Thanks I'll go back and check what I've done and I'll close this as it doesn't seem to be an issue with the code here.
