### ISSUE TITLE
Alternative Store to buy the Android App?

### ISSUE THREAD

**Issue by aolszowka** [snowzach/echbt#6]
Do you provide an alternative store to purchase the application (ideally directly or via the Amazon App Store?) I have an unlocked Sport Connect Plus with the Tablet.

However because it does not have Google Play Services it does not have the Google Play Store on the device. The best I can get on there is the Amazon App Store (at least for Purchases, other stores like F-Droid work as does side loading the Application Directly).

I've got QZ on it and that works (purchased via the Amazon App Store), but I do not like that QZ does not overlay whereas it looks like this Application would. I am looking to overlay PlutoTV while spinning.

That tablet advertises as a rk3288 which is a armeabi-v7a device; its running Android 9.

**Comment by goofygrin** [comment]
I used blue stacks on my computer to buy and install the app. Then apk extractor to extract the apk. Uploaded to google drive from blue stacks and then downloaded on my bike. Installed and works great.

**Comment by zbup** [comment]
Ha! Nice work!

**Comment by aolszowka** [comment]
I ended up doing something similar:

1. On my older Motorola Cruise 5e (which is an armv7 device, same as the Echelon Sport Connect Table) I installed SAI (https://github.com/Aefyr/SAI) and purchased EchBT from the Play Store.
2. Using SAI I extracted the Split APK and saved it to the device.
3. I then used ShareDrop.io (on the Firefox Browser on both Devices) to transfer the APK between the Motorola Cruise and the Echelon Tablet. This is done because I wanted to avoid giving my credentials to the Echelon Tablet.
4. I installed SAI on the Echelon Tablet using the Aurora Store (https://gitlab.com/AuroraOSS/AuroraStore)
5. Using SAI I installed the APK.

Works great on my Sport Connect Plus.

You need to use SAI because it is the only APK Extractor/Installer that I have found that allows for Split APKs to be backed up and then reinstalled, pros are that it is also open source which at the time of install for me looked "clean". It properly handles the APK splitting by creating its own packaging system (basically a ZIP File). YMMV always trust but verify for yourself.

Obviously you're now "stuck" at this version, but who needs updates?

If you were not concerned about your Google Credentials you could have used the Aurora Store and purchased it directly on the Tablet, but sharing account information on a rooted device with a third party app (even though its open source) isn't ideal for my threat model, but if it is for yours `YOLO`.

The overlay works extremely well, I do wish that it showed mileage like QZ does but I can live without it so long as I have the overlay (so I can watch PlutoTV), any chance we can get it?

**Comment by zbup** [comment]
Is mileage somewhat arbitrary? It wouldn't probably be that hard to fudge some number together but I would need to know what cadence dictated what MPH... Is there some standard for stationary bikes on what cadence equals what MPH?

**Comment by aolszowka** [comment]
@zbup Not sure honestly; QZ gives a number, if its legit or not unclear. Pretty new to indoor cycling but if you could give the diameter of the fly wheel couldn't you calculate it like a lot of bike computers do? Props for making it configurable.

Realistically I'm just using it to see if I'm improving, its just a number, which reading more about how the indoor guys and gals do it should be that power number.

I'm happy to open a new issue and beta test it for you, I'm not an Android Developer by trade but I know enough to be dangerous as a Build Master (I'm comfortable with ADB and as you can see know how to get it working!).

**Comment by aolszowka** [comment]
Sorry to double post; but I wanted to call out that the thread from the original implementation of this bike in QZ had a lot of great information in it https://github.com/cagnulein/qdomyos-zwift/issues/62 the guy was able to provide a btsnoop_hci.log. Seeing as you've already decoded some of the messages we're probably past that but I haven't loaded up the log in wireshark, but the comments seem to indicate that distance might have been included in the message?

Further down a lot of research is done to try and narrow it down, his spreadsheet is still up https://docs.google.com/spreadsheets/d/1OHoZsEx-0i6ETi83g0uI7q3Ug8ET0u-fVVSm8rAUC3s/edit#gid=1151120114 (I grabbed a copy) which shows all of his work.

**Comment by snowzach** [comment]
Okay, I added distance to the display... It's actually open source.. https://github.com/snowzach/echbt-android

**Comment by snowzach** [comment]
I realized I submitted it to Amazon ages ago and it was rejected for reasons unknown... I just submitted it again and I think it took this time.

**Comment by snowzach** [comment]
Hey! They actually accepted it.

**Comment by aolszowka** [comment]
We must maintain similar hours, I was just looking for it on Amazon, do you have a direct link?

**Comment by snowzach** [comment]
No... I can't seem to search for it or find it... I don't have an Amazon device so I can't seem to open their app store.  In theory it should be under `EchBT Stats`

**Comment by aolszowka** [comment]
No dice yet; I'll check this afternoon.

>I don't have an Amazon device so I can't seem to open their app store

FWIW you don't need an Amazon Device to load up the app store. They distribute an APK on their site https://www.amazon.com/gp/mas/get/android which is why it usually get used by those with devices that do not support Google Play Services. I'm not sure if their fee structure is better but I haven't looked recently. Historically they would have given free AWS credits and I think its a flat 20% but don't quote me on that.

All that to say always best to be in multiple stores to avoid relying too much on a single storefront (looking at you Apple App Store!)

**Comment by aolszowka** [comment]
@snowzach Double Posting to say you're LIVE on the Amazon App Store Here: https://www.amazon.com/dp/B08W24TT42

I purchased it but I do not seem to see it on the Echelon Tablet, looking at it my guess is an armeabi-v7a binary was not uploaded. I'm not familiar with how Amazon's app store handles this (in the Google Play Store you'd upload the large bundle and then they'd do the hard work to split it for the various devices) and I'm only guessing based on the fact that only my absolute newest Amazon Devices are compatible:

![image](https://user-images.githubusercontent.com/2592881/211451894-5d171eca-c82c-45c4-8f17-ea1912db1378.png)

Any chance you can take a look at it? Otherwise I'll get off my duff and work towards a build for you locally!

**Comment by snowzach** [comment]
Hmm... It appears to be a version problem with the minimum android sdk... Do you know what version you need? It's currently set at 21.

**Comment by aolszowka** [comment]
Should be good; here's the output from ADB:

```
rk3288:/ $ getprop ro.build.version.release
9
rk3288:/ $ getprop ro.build.version.sdk
28
```

FWIW the version from the Google Play Store last released in February of 2022 works without issue on the bike

EDIT: Adding `cat /system/build.prop` for completeness:

```
rk3288:/ # cat /system/build.prop

# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=PI
ro.build.display.id=Z33P-JST-90-9.0-10.1-SW0.2-20210313-TV103WUM-LL0
ro.build.version.incremental=152733
ro.build.version.sdk=28
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=9
ro.build.version.security_patch=2020-03-05
ro.build.version.base_os=
ro.build.version.min_supported_target_sdk=17
ro.build.date=Sat Mar 13 15:27:25 CST 2021
ro.build.date.utc=1615620445
ro.build.type=userdebug
ro.build.user=root
ro.build.host=adw-PowerEdge-R740
ro.build.tags=test-keys
ro.build.flavor=rk3288-userdebug
ro.sf.lcd_density=160
ro.sf.hwrotation=0
persist.vendor.rootservice=1
ro.build.system_root_image=true
ro.product.model=rk3288
ro.product.brand=rockchip
ro.product.name=rk3288
ro.product.device=rk3288
ro.config.media_vol_default=8
ro.config.alarm_vol_default=8
ro.config.system_vol_default=8
ro.config.vc_call_vol_steps=16
ro.config.media_vol_steps=16
ro.config.alarm_vol_steps=16
# ro.product.cpu.abi and ro.product.cpu.abi2 are obsolete,
# use ro.product.cpu.abilist instead.
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.manufacturer=rockchip
ro.product.locale=en-US
ro.wifi.channels=
# ro.build.product is obsolete; use ro.product.device
ro.build.product=rk3288
# Do not try to parse description, fingerprint, or thumbprint
ro.build.description=rk3288-userdebug 9 PI 152733 test-keys
ro.build.fingerprint=rockchip/rk3288/rk3288:9/PI/root03131527:userdebug/test-keys
ro.build.characteristics=tablet
# end build properties

#
# ADDITIONAL_BUILD_PROPERTIES
#
ro.bionic.ld.warning=1
ro.art.hiddenapi.warning=1
ro.treble.enabled=true
persist.sys.dalvik.vm.lib.2=libart.so
dalvik.vm.isa.arm.variant=cortex-a15
dalvik.vm.isa.arm.features=default
dalvik.vm.lockprof.threshold=500
net.bt.name=Android
dalvik.vm.stack-trace-dir=/data/anr
ro.expect.recovery_id=0xdcc240a3ccb3fc3ad3fe27d3751b8d8f594b7233000000000000000000000000
```

**Comment by snowzach** [comment]
Ahhhh I know what it is... It requires GPS permissions... Let me see if I can remove that need.. It's something to do with Bluetooth...

**Comment by snowzach** [comment]
Okay, I figured out how to keep location services (required for bluetooth) but not require it to have GPS hardware. I submitted the update...

**Comment by aolszowka** [comment]
@snowzach I'm also always willing to try a beta, I have the ability to side load it my username at Google's email service :)

**Comment by snowzach** [comment]
It won't let me mail it... It's submitted... I posted it to Play Store and Amazon.. It was a very minor change, I doubt it will take long to approve it.. I am nearly certain that will fix the issue.

**Comment by aolszowka** [comment]
@snowzach Sweet 1.12 (which has the GPS Fixes along with the Distance Calculations) is live on the Amazon App Store. I loaded it on my device and it worked without issue! Thank you :)

**Comment by snowzach** [comment]
Awesome! No prob
