### ISSUE TITLE
Availability on non-Google Play stores

### ISSUE THREAD

**Issue by aaciii** [snowzach/echbt#9]
For people that have jail broken their Echelon-provided tablet, there is no easy way to buy/get EchBT-stats because the tablet does not support Google Play.

I was able to extract and move the APK to the tablet from another Android device, but it would be great if you offered the app through the Amazon App Store or another source.

**Comment by snowzach** [comment]
I just added it to Amazon the other day. Have a search..

**Comment by aaciii** [comment]
Oh great!!

**Comment by aaciii** [comment]
Also fyi I added these enhancement suggestion/items as issues -- but in GitHub I don't actually see them after I submit.  (I do get notifications when you comment).   Any idea why?

**Comment by snowzach** [comment]
Nope.. not sure why..
